Controllers/EstudianteController.cs
using Modulo_Asesorias.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Security.Claims;

namespace Modulo_Asesorias.Controllers { 

    public class EstudianteController : Controller
    {
        public IActionResult Reservar()
        {
            List<Usuario> profesores = new List<Usuario>();


            using (var db = new AsesoriaContext())
            {
                // var a = db.Database.ExecuteSqlInterpolated("SELECT persona.NOMBRE1_PERSONA , persona.APELLIDO1_PERSONA ,GROUP_CONCAT(DISTINCT  asignatura.NOMBRE_ASIGNATURA) From usuario INNER JOIN persona ON usuario.FK_ID_PERSONA = persona.ID_PERSONA INNER JOIN agenda ON agenda.FK_ID_PROFESOR = usuario.ID_USUARIO INNER JOIN impartir ON impartir.FK_ID_USUARIO= usuario.ID_USUARIO INNER JOIN asignatura ON impartir.FK_ID_ASIGNATURA=asignatura.ID_ASIGNATURA WHERE usuario.FK_ID_PERMISO=1 GROUP BY persona.NOMBRE1_PERSONA, persona.APELLIDO1_PERSONA;");

               
                 profesores = (from usuario in db.Usuarios
                                  join persona in db.Personas on usuario.FkIdPersona equals persona.IdPersona
                                  join agenda in db.Agenda on usuario.IdUsuario equals agenda.FkIdProfesor
                                  join impartir in db.Impartirs on usuario.IdUsuario equals impartir.FkIdUsuario
                                  group new { usuario, persona, impartir } by new { usuario.IdUsuario, usuario.FkIdPersona, persona.Nombre1Persona, persona.Apellido1Persona } into g
                                  select new Usuario
                                  {
                                      IdUsuario = g.Key.IdUsuario,
                                      FkIdPersona = g.Key.FkIdPersona,
                                      FkIdPersonaNavigation = new Persona
                                      {
                                          Nombre1Persona = g.Key.Nombre1Persona,
                                          Apellido1Persona = g.Key.Apellido1Persona,
                                      },
                                      Impartirs = g.Select( x => new Impartir
                                      {
                                          FkIdAsignatura = x.impartir.FkIdAsignatura,
                                          FkIdAsignaturaNavigation = new Asignatura
                                          {
                                              NombreAsignatura = x.impartir.FkIdAsignaturaNavigation.NombreAsignatura
                                          }
                                      }).Distinct().ToList()
                                  }).ToList();
                return View(profesores);
            }
        }

        [HttpPost]
        public  IActionResult obtenerFechas(int id_profesor)
        {
            using (var db = new AsesoriaContext())
            {
                var fechas = (from usuario in db.Usuarios
                              join agenda in db.Agenda on usuario.IdUsuario equals agenda.FkIdProfesor
                              where usuario.IdUsuario == id_profesor && agenda.FkIdEstudiante == null
                              select agenda.FechaAgenda.ToString()).Distinct().ToList();
                 return Json(fechas);             
            }
            
        }

        [HttpPost]
        public IActionResult obtenerHoras(DateOnly fecha, int idprofesor) {

            using (var db = new AsesoriaContext())
            {
                var horas = (from Agenda in db.Agenda
                              where Agenda.FechaAgenda == fecha && Agenda.FkIdProfesor == idprofesor && Agenda.FkIdEstudiante == null
                              select new Agendum {
                                IdAgenda = Agenda.IdAgenda,
                                HorainicioAgenda = Agenda.HorainicioAgenda,
                              }).ToList();
                return Json(horas);
            }
        }

        [HttpPost]
        public IActionResult crearReserva( int ida)
        {
            using (var db = new AsesoriaContext())
            {
                var a = Int32.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Actor).Value + "");

                var agenda = db.Agenda.Where(x => x.IdAgenda == ida).FirstOrDefault();

                agenda.FkIdEstudiante = a;
                
                db.SaveChanges();

                return RedirectToAction("Index","Home");
            }
        }

        public IActionResult verAsesorias()
        {

            List<Agendum> listaAsesorias = new List<Agendum>();
            using (var db = new AsesoriaContext())
            {
                DateOnly fechaActual = DateOnly.FromDateTime(DateTime.Today);
                var a = Int32.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Actor).Value + "");

                listaAsesorias = db.Agenda.Include(x => x.FkIdEstudianteNavigation).ThenInclude(x => x.FkIdPersonaNavigation)
                                    .Include(x => x.FkIdProfesorNavigation).ThenInclude(x => x.FkIdPersonaNavigation)
                                    .Where(x => x.FkIdEstudiante == a && x.FechaAgenda > fechaActual).ToList();

            }
            return View(listaAsesorias);

        }

    }
}

Views/Shared/Layout_estudiante.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/Img/uniamazonia.png" type="image/x-icon">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">Asesorias</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Reservar","Estudiante")">Reservar asesoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("verAsesorias", "Estudiante")">Ver Asesorias </a>
                        </li>                        
                    </ul>
                </div>
                <div class="d-flex">
                    <a class="nav-link" href="@Url.Action("salir", "Home")">Cerrar sesion</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer fixed-bottom">
        <div class="container">
            &copy; 2023 - Universudad de la Amazonia
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/Layout_profesor.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/Img/uniamazonia.png" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">Asesorias</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("crearHorario","Profesor")">Crear Horario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Horario", "Profesor")">Ver Horario</a>
                        </li>
                    </ul>
                </div>
                <div class="d-flex">
                    <a class="nav-link" href="@Url.Action("salir", "Home")">Cerrar sesion</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer fixed-bottom">
        <div class="container">
            &copy; 2023 - Universudad de la Amazonia
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>